version: '3.8'

services:
    backend:
        build: ./Back
        env_file:
            - .env
        volumes:
            - ${BACKPATH}:/Back:rw
            - ${DATAPATH}:/Data:rw
        ports: 
            - 4280:4280
        networks:
            - solene_network

    frontend:
        build: ./Front
        volumes:
            - ${FRONTPATH}:/Front:rw
        ports: 
            - ${EXTPORT}:5173
        networks:
            - solene_network

networks:
    solene_network:
        driver: "bridge"
        ipam:
            driver: default
            config:
                - subnet: ${SUBNET}
