version: '3.8'

services:
    backend:
        build: ./Back
        env_file:
            - .env
        environment:
            # Change this if you wish to have the FRONT server on a different machine than the BACK
            - FRONT_SERVER=${BACK_SERVER}:${EXTPORT}
            - HPO_FILE=/exomiser_db/hp.obo
        volumes:
            - ${BACKPATH}:/Back:rw
            - ${DATAPATH}:/Data:rw
            - ${EXOMISER_DB}:/exomiser_db:ro
        ports:
            - ${BACK_PORT}:4280
        networks:
            - solene_network

    frontend:
        build: ./Front
        environment:
            - VITE_BACKEND=${BACK_SERVER}:${BACK_PORT}
        volumes:
            - ${FRONTPATH}:/Front:rw
        ports:
            - ${EXTPORT}:5173
        networks:
            - solene_network

networks:
    solene_network:
        driver: "bridge"
        ipam:
            driver: default
            config:
                - subnet: ${SUBNET}
